### ISSUE TITLE
Processed outputs should be till cut_out wind speed at reference height

### ISSUE THREAD

**Issue by DylanEij** [awegroup/FixedWingGG-Power#14]
I think the following line:
https://github.com/awegroup/FixedWingGG-Power/blob/360386fa690db49c0741f6008908fde8364a60eb/Src/main.m#L71C10-L71C39

Should be changed to:
```Matlab
if vw(i)>=processedOutputs.cutIn && vw(i)<=max(processedOutputs.vw_100m_operRange)
```

**Comment by rishikeshsjoshi** [comment]
The modification you propose is considering wind speed at 100m height. But, the line you are referring to is meant for the wind speeds at pattern height, which still should have a chosen cutout wind speed of 25m/s. When translated to 100m height, this value is smaller.

**Comment by rishikeshsjoshi** [comment]
fixed
